name: CI
on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - ".github/workflows/**"
      - "Package.swift"
      - "Source/**"
      - "Tests/**"    
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - ".github/workflows/**"
      - "Package.swift"
      - "Source/**"
      - "Tests/**"    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No build required"'