name: Upload

# read-write repo token
# access to secrets
on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  upload:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - uses: actions/checkout@v3
      - run: ls
      - name: Dump context
        run: echo '${{ toJSON(github) }}'
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ${{ github.event.workflow_run.workflow_id }}
          workflow_conclusion: success
          path: .
          if_no_artifact_found: 'ignore'
      - name: Set found_files
        id: set_found_files
        run: |
          if [ -f coverage/HelloWorld.swift ]; then
            echo "found_files=true" >> $GITHUB_OUTPUT
          else
            echo "found_files=false" >> $GITHUB_OUTPUT
          fi  
      - run: ls
      - run: |
          mv coverage/HelloWorld.swift .
          rm -rf coverage
          ls
        if: steps.set_found_files.outputs.found_files == 'true'   
      - run: cat HelloWorld.swift
        if: steps.set_found_files.outputs.found_files == 'true'   
